// <auto-generated />
using System;
using ActivityTracking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivityTracking.Infrastructure.Migrations
{
    [DbContext(typeof(ActivityDbContext))]
    [Migration("20260312070837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityTracking.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.EnergyUsage", b =>
                {
                    b.HasBaseType("ActivityTracking.Domain.Entities.Activity");

                    b.Property<double>("CarbonEmission")
                        .HasColumnType("float");

                    b.Property<double>("UnitsConsumed")
                        .HasColumnType("float");

                    b.ToTable("EnergyUsages", (string)null);
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.TransportActivity", b =>
                {
                    b.HasBaseType("ActivityTracking.Domain.Entities.Activity");

                    b.Property<double>("CarbonEmission")
                        .HasColumnType("float");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TransportActivities", (string)null);
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.WasteActivity", b =>
                {
                    b.HasBaseType("ActivityTracking.Domain.Entities.Activity");

                    b.Property<double>("CarbonEmission")
                        .HasColumnType("float");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.ToTable("WasteActivities", (string)null);
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.EnergyUsage", b =>
                {
                    b.HasOne("ActivityTracking.Domain.Entities.Activity", null)
                        .WithOne()
                        .HasForeignKey("ActivityTracking.Domain.Entities.EnergyUsage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.TransportActivity", b =>
                {
                    b.HasOne("ActivityTracking.Domain.Entities.Activity", null)
                        .WithOne()
                        .HasForeignKey("ActivityTracking.Domain.Entities.TransportActivity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityTracking.Domain.Entities.WasteActivity", b =>
                {
                    b.HasOne("ActivityTracking.Domain.Entities.Activity", null)
                        .WithOne()
                        .HasForeignKey("ActivityTracking.Domain.Entities.WasteActivity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
